"""
These are modified examples for test purposes.
Values where chosen in accordance to existing categories:

Example:
    - for each field from MERGE_BY_MOST_FREQUENT, values where chosen such that the most frequent would be merged
"""

SAMPLE_PRODUCTS = {
    5554: {
        'unspsc': 'Pipe connectors',
        'root_domain': 'studio-atcoat.com',
        'page_url': 'https://www.harebueng.co.za/antioxidant-dbha-rubber-in-brazil.html',
        'product_title': 'Rubber Accelerator MBT',
        'product_summary': 'Rubber Accelerator MBT is a high-quality rubber accelerator used for various types of rubber. It is a Mercaptobenzothiazole with CAS# 149-30-4. It is priced between $1.81 - $1.90 per kilogram with a minimum order of 1000 kilograms.',
        'product_name': 'Rubber Accelerator',
        'product_identifier': 'CAS: 149-30-4',
        'brand': 'DeRoyal',
        'intended_industries': ('Manufacturing',),
        'applicability': ('Rubber Acceleration',),
        'eco_friendly': None,
        'ethical_and_sustainability_practices': (),
        'production_capacity': ((('quantity', 1500), ('time_frame', 'Month'), ('type', 'exact'), ('unit', 'Tons')),),
        'price': (),
        'materials': (),
        'ingredients': (),
        'manufacturing_countries': (),
        'manufacturing_year': -1,
        'manufacturing_type': (),
        'customization': (),
        'packaging_type': (),
        'form': (),
        'size': (
            (('dimension', 'Weight'), ('qualitative', False), ('type', 'exact'), ('unit', 'kg'), ('value', '1000')),
        ),
        'color': (),
        'purity': (),
        'energy_efficiency': None,
        'pressure_rating': (),
        'power_rating': (),
        'quality_standards_and_certifications': (),
        'miscellaneous_features': ('Mercaptobenzothiazole',),
        'description': '"Rubber Accelerator" is a high-quality rubber accelerator used for various types of rubber, featuring a Mercaptobenzothiazole structure with CAS number 149-30-4.',
        'base_root_domain': 'harebueng',
        'details': {},
        'id': 5554,
    },
    7652: {
        'unspsc': 'Curing agents',
        'root_domain': 'harebueng.co.za',
        'page_url': 'https://www.harebueng.co.za/rubber-accelerator-tmq-rubber-accelerator-tmq-suppliers.html',
        'product_title': 'Rubber Accelerator TMQ',
        'product_summary': 'Rubber Accelerator TMQ is a specialized chemical compound used in the rubber industry to enhance the acceleration of rubber vulcanization processes. It is available in various forms, including powder, spray-dried oil powder, and masterbatch, and is applicable in multiple industries such as tire and tubing, consumer goods, construction, electrical insulation, and other sectors. The product is designed to improve the performance and durability of rubber products by accelerating the vulcanization process, which is crucial for the manufacturing of high-quality rubber goods. The Rubber Accelerator TMQ is manufactured and supplied by various companies, ensuring a wide range of availability and supply options. The product is essential for industries requiring efficient and reliable rubber vulcanization, and its use is supported by comprehensive market research and forecasts, indicating its significant growth potential in the global market.',
        'product_name': 'Rubber Accelerator TMQ',
        'product_identifier': (),
        'brand': 'Nutrena',
        'intended_industries': ('Rubber Industry',),
        'applicability': ('Rubber Vulcanization',),
        'eco_friendly': None,
        'ethical_and_sustainability_practices': (),
        'production_capacity': (),
        'price': (),
        'materials': (),
        'ingredients': (),
        'manufacturing_countries': (),
        'manufacturing_year': -1,
        'manufacturing_type': (),
        'customization': ('Available in various forms including powder, spray-dried oil powder, and masterbatch',),
        'packaging_type': (),
        'form': ('Powder', 'Powder'),
        'size': (),
        'color': (),
        'purity': (),
        'energy_efficiency': None,
        'pressure_rating': (),
        'power_rating': (),
        'quality_standards_and_certifications': (),
        'miscellaneous_features': (
            'Available in powder, spray-dried oil powder, and masterbatch',
            'Essential for industries requiring efficient and reliable rubber vulcanization',
        ),
        'description': '"Rubber Accelerator TMQ" is a specialized chemical compound used in the rubber industry to enhance the acceleration of rubber vulcanization processes. It is available in various forms including powder, spray-dried oil powder, and masterbatch, and is applicable in multiple industries such as tire and tubing, consumer goods, construction, electrical insulation, and other sectors. The product is designed to improve the performance and durability of rubber products by accelerating the vulcanization process, crucial for the manufacturing of high-quality rubber goods.',
        'base_root_domain': 'harebueng',
        'details': {},
        'id': 7652,
    },
    9971: {
        'unspsc': 'Faucets or taps',
        'root_domain': 'harebueng.co.za',
        'page_url': 'https://www.harebueng.co.za/antiscorching-pvi-antiscorching-pvi-suppliers-poland.html',
        'product_title': 'Rubber Accelerator TMQ',
        'product_summary': 'TMTD (Tetramethylthiuram Disulfide) is a highly effective accelerator used primarily in rubber processing, particularly for low-temperature cures. It is also widely applicable as a fungicide and seed soaking agent in agriculture. The chemical name for TMTD is Tetramethyl thiuram disulfide, with a molecular formula of C6H12N2S4 and a molecular weight of 240.41. It has a purity of ≥96% and is identified by the CAS number 137-26-8 and EINECS number 205-286-2. TMTD is a general-purpose accelerator for both natural and synthetic rubbers, especially those of the IIR and CR types. It can be used as a single accelerator, as a secondary accelerator, or as a sulfur donor in most sulfur-cured elastomers. The product is known for its fast vulcanization rate, high maximum torque (Tmax), and excellent mechanical properties such as hardness, 300% modulus, tensile strength, and elongation. TMTD is compatible with natural and synthetic rubber and latex, making it a versatile choice for various rubber processing applications. It is also used in continuous vulcanization processes. The product is supplied in a white powder form and has an initial melting point of at least 142.0°C, with a heating loss percentage of ≤ 0.40%. TMTD is a sulfur donor, enhancing the vulcanization process by providing a fast cure rate and high mechanical properties. It is suitable for use in both natural and synthetic rubber and latex, making it a reliable choice for various industrial applications.',
        'product_name': 'TMTD',
        'product_identifier': 'CAS: 137-26-8',
        'brand': None,
        'intended_industries': ('Rubber Processing', 'Agriculture'),
        'applicability': ('Rubber Processing', 'Fungicide', 'Seed Soaking'),
        'eco_friendly': True,
        'ethical_and_sustainability_practices': (
            'adhering to environmental standards and regulations',
            'designed to be recyclable',
        ),
        'production_capacity': (
            (('quantity', 60), ('time_frame', 'Year'), ('type', 'min'), ('unit', 'Tons')),
            (('quantity', 70), ('time_frame', 'Year'), ('type', 'max'), ('unit', 'Tons')),
        ),
        'price': (
            (('amount', 1.809999942779541), ('currency', 'USD'), ('type', 'min')),
            (('amount', 1.899999976158142), ('currency', 'USD'), ('type', 'max')),
        ),
        'materials': ('Ceramic'),
        'ingredients': ('Vanilla', 'Salt'),
        'manufacturing_countries': (),
        'manufacturing_year': -1,
        'manufacturing_type': ('Turnkey',),
        'customization': ('Various types of grinding wheels available',),
        'packaging_type': (),
        'form': ('Powder',),
        'size': (
            (('dimension', 'Diameter'), ('qualitative', False), ('type', 'min'), ('unit', 'mm'), ('value', '115')),
            (('dimension', 'Diameter'), ('qualitative', False), ('type', 'max'), ('unit', 'mm'), ('value', '450')),
        ),
        'color': ((('original', 'Blue'), ('simple', 'White')),),
        'purity': ((('qualitative', False), ('type', 'exact'), ('unit', None), ('value', '96.0')),),
        'energy_efficiency': None,
        'pressure_rating': (),
        'power_rating': (
            (('qualitative', False), ('type', 'exact'), ('unit', 'W'), ('value', '1200.0')),
            (('qualitative', True), ('type', 'exact'), ('unit', None), ('value', 'high')),
        ),
        'quality_standards_and_certifications': ('ISO Certified',),
        'miscellaneous_features': ('Initial Melting Point: At least 142.0°C', 'Heating Loss Percentage: ≤ 0.40%'),
        'description': '"TMTD" is a highly effective accelerator used in rubber processing, particularly for low-temperature cures, and serves as a fungicide and seed soaking agent in agriculture. It is compatible with both natural and synthetic rubbers, including IIR and CR types, and is used as a single accelerator, secondary accelerator, or sulfur donor in sulfur-cured elastomers. The product is known for its fast vulcanization rate and excellent mechanical properties, making it a versatile choice for various rubber processing applications.',
        'base_root_domain': 'harebueng',
        'details': {},
        'id': 9971,
    },
    10275: {
        'unspsc': 'Curing agents',
        'root_domain': 'advancedpressuresystems.ca',
        'page_url': 'https://advancedpressuresystems.ca/1',
        'product_title': 'Rubber Accelerator TMTD IPPD',
        'product_summary': 'Rubber Accelerator TMTD IPPD, also known as Tetramethylthiuram Disulfide, is a highly effective ultra-accelerator widely used in rubber processing. It is primarily utilized in low-temperature cures, either alone or as an activator for other accelerators, particularly thiazoles. This product is available in a white or light gray powder or granule form with a density of 1.29. It is soluble in benzene, acetone, chloroform, CS2, and partially soluble in alcohol, diethyl ether, and CCl4, but insoluble in water, gasoline, and alkali with lower concentrations. TMTD IPPD is identified by the CAS number 137-26-8 and adheres to the HG/T 2334-2007 standard. It is commonly used as a single accelerator, secondary accelerator, or as a sulfur donor in most sulfur-cured elastomers, providing fast cure rates and scorchy properties. It is particularly effective in NBR, EPDM, and other rubber elastomers or blends, and is often required to be combined with zinc oxide and a fatty acid for effective use. The product is manufactured in Pakistan and is known for its high purity, with a minimum purity of 96%. It is widely used in the rubber industry for its ability to retard CR and act as an effective accelerator for low-temperature cures.',
        'product_name': 'Rubber Accelerator',
        'product_identifier': 'CAS: 137-26-8',
        'brand': 'Nutrena',
        'intended_industries': ('Rubber Industry',),
        'applicability': ('Rubber Processing',),
        'eco_friendly': None,
        'ethical_and_sustainability_practices': (
            'meet the E1 formaldehyde standards',
            'CVI Green products',
            'extremely low in emissions',
            'ISO 9001:2015 standard',
            'designed to be recyclable',
        ),
        'production_capacity': ((('quantity', 60000), ('time_frame', 'Month'), ('type', 'exact'), ('unit', 'Units')),),
        'price': (),
        'materials': ('Ceramic', 'Ceramic powder'),
        'ingredients': ('Vanilla', 'Spiced'),
        'manufacturing_countries': ('PK',),
        'manufacturing_year': -1,
        'manufacturing_type': (),
        'customization': ('Various colors available',),
        'packaging_type': ('Cartons',),
        'form': ('Powder', 'Granules'),
        'size': (
            (('dimension', 'Length'), ('qualitative', False), ('type', 'exact'), ('unit', 'mm'), ('value', '127')),
            (('dimension', 'Width'), ('qualitative', False), ('type', 'exact'), ('unit', 'mm'), ('value', '82')),
        ),
        'color': ((('original', 'Blue'), ('simple', 'Blue')),),
        'purity': (
            (('qualitative', False), ('type', 'exact'), ('unit', None), ('value', '97.0')),
            (('qualitative', True), ('type', 'exact'), ('unit', None), ('value', 'high')),
        ),
        'energy_efficiency': (
            (
                ('exact_percentage', 40.0),
                ('max_percentage', None),
                ('min_percentage', None),
                ('qualitative', 'high'),
                ('standard_label', None),
            ),
        ),
        'pressure_rating': ((('qualitative', True), ('type', 'exact'), ('unit', None), ('value', 'high')),),
        'power_rating': (),
        'quality_standards_and_certifications': ('HG/T 2334-2007',),
        'miscellaneous_features': (
            'Solubility in benzene, acetone, chloroform, CS2, and partially soluble in alcohol, diethyl ether, and CCl4',
            'Insoluble in water, gasoline, and alkali with lower concentrations',
        ),
        'description': '"Rubber Accelerator TMTD IPPD" is a highly effective ultra-accelerator used in the rubber processing industry, particularly in low-temperature cures. It is soluble in various organic solvents and insoluble in water and most alkanes, ensuring its effectiveness in specific rubber types such as NBR and EPDM. Manufactured in Pakistan, this product adheres to the HG/T 2334-2007 standard and is known for its high purity, with a minimum purity of 96%.',
        'base_root_domain': 'harebueng',
        'details': {},
        'id': 10275,
    },
}

SAMPLE_PRODUCTS_ID_TO_PRODUCT_IDENTIFIER_MAPPING = {
    5554: 'CAS: 149-30-4',
    7652: (),
    9971: 'CAS: 137-26-8',
    10275: 'CAS: 137-26-8',
}

COMPUTE_FREQUENCIES_RESULT = {
    'product_name': {'Rubber Accelerator': 2, 'Rubber Accelerator TMQ': 1, 'TMTD': 1},
    'product_title': {'Rubber Accelerator MBT': 1, 'Rubber Accelerator TMQ': 2, 'Rubber Accelerator TMTD IPPD': 1},
    'unspsc': {'Pipe connectors': 1, 'Curing agents': 2, 'Faucets or taps': 1},
    'root_domain': {'studio-atcoat.com': 1, 'harebueng.co.za': 2, 'advancedpressuresystems.ca': 1},
    'brand': {'DeRoyal': 1, 'Nutrena': 2, None: 1},
}

ID_TO_PRODUCT_IDENTIFIER_MAPPING = {
    1559: (),
    1567: (),
    1684: 'Part_Number: ZDC (EZ) and ZDEC',
    2518: (),
    3557: (),
    3993: 'CAS: 102-06-7',
    5554: 'CAS: 149-30-4',
    6958: (),
    7652: (),
    9971: 'CAS: 137-26-8',
    10275: 'CAS: 137-26-8',
    15574: (),
    17230: (),
    19657: (),
}
